[fantasy]
api_token = "__Secure-next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..iCP_-u-Jjl5EqUcs.X6C8bfW5bonyRXufGIaEw4CBXN2G0OYNdrSPpAROVRnpBXU3VozIqtL1mdAjXDdOhAA1R5uLAlTxlNad5_zkLhB981ctbB1YTf9jYZCNM3zkx16TXHJcQElW9raPVNpbeChdABlPAJ-3hQ2kXjsECk5zQW2TgGQKKLk_Rgv4ioIHhfftVkTVM2529sNe29FzzjXU01klUeC-blQDSzsEn74.8BcKR3XmfpRfzEgoPi_EIg"
base_url = "https://fantasy.europeanleague.football/_next/data/rSWNzuZiOSdsD3NgdLiyj/{}.json"

[elf]
base_url = "https://europeanleague.football/api/{}"

[server]
runOnSave = true